#!/bin/bash

#-------------------------------------------------------------------------------
# GPG-AGENT

GPG_AGENT_ENV="$HOME/.gnupg/gpg-agent.env"
if [[ -e "$GPG_AGENT_ENV" ]] && kill -0 $(grep GPG_AGENT_INFO "$GPG_AGENT_ENV" | cut -d: -f 2) 2>/dev/null; then
    eval "$(cat "$GPG_AGENT_ENV")"
else
    eval "$(gpg-agent --daemon --enable-ssh-support --write-env-file "$GPG_AGENT_ENV")"
fi
export GPG_AGENT_INFO  # the env file does not contain the export statement
export SSH_AUTH_SOCK   # enable gpg-agent for ssh


#-------------------------------------------------------------------------------
# SSH-AGENT

SSH_ENV="$HOME/.ssh/environment"

function start_agent {
     echo "Initialising new SSH agent..."
     /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
     echo succeeded
     chmod 600 "${SSH_ENV}"
     source "${SSH_ENV}" > /dev/null
     /usr/bin/ssh-add;
}

# Source SSH settings, if applicable

if [ -f "${SSH_ENV}" ]; then
     source "${SSH_ENV}" > /dev/null
     ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || start_agent
else
     start_agent;
fi
