#!/bin/bash

#-------------------------------------------------------------------------------
# SVN support

if command -v svn >/dev/null 2>&1 ; then
    function svnc {
        ~/.bash/scripts/svnc.py "$@"
    }
fi
