#!/bin/bash

#-------------------------------------------------------------------------------
# SVN support

if command -v svn >/dev/null 2>&1 ; then
    function svnc {
        "${DEPLOY_DIR}/.bash/scripts/svnc.py" "$@"
    }
fi
